### ISSUE TITLE
Can't use the workflow on M1 BigSur

### ISSUE THREAD

**Issue by rashad** [jarlefosen/alfred-gcloud-shortcuts#27]
Hey there, am I the only one getting this kind of error when trying to initially refresh the project list to be able to use it ? 
![image](https://user-images.githubusercontent.com/11599358/118870668-1a1d0e00-b8e7-11eb-87c1-a1ca1e232b00.png)

NB: I'm running BigSur 11.2.2 on an M1 Macbook Air

**Comment by jarlefosen** [comment]
Hi, I wonder if this could be due to gcloud application credentials missing.

Could you follow the last point in the requirements paragraph in README?
https://github.com/jarlefosen/alfred-gcloud-shortcuts#requirements

I don't have an M1 machine and haven't upgraded to Big Sur quite yet, so I don't really have a test environment for this issue.
Please report back if saving the application credentials works or not.

**Comment by rashad** [comment]
Oh my God that was it ! I'm so sorryyyyyyyy I did not think of this auth default login with Google SDK 🤦 
Thank you so so much for your help
